public class pp6 {

    
    public void test(){
        System.debug('Helllo ......');
    }
    
    @testVisible
    private void test2(){
        System.debug('Ytstuchkcd...kdsjd');
        System.debug('Ytstuchkcd...kdsjd');
        System.debug('Ytstuchkcd...kdsjd');
        System.debug('Ytstuchkcd...kdsjd');
    }
    
    
    public integer test3(integer x, integer b){
        integer a = x+b;
        return a;
    }
    
    
    
}